### ISSUE TITLE
Bug in the ECO database

### ISSUE THREAD

**Issue by ilaripih** [jeremybernstein/cutechess#2]
I noticed that TCEC detected the "1. c4 c5" opening as Benoni (A56) in this game: http://tcec.chessdom.com/archive.php?se=8&st=2&ga=118

But shouldn't all variations of Benoni always start with d4? I checked that the official CuteChess with its internal ECO database correctly detects the opening as English (A34).

**Comment by jeremybernstein** [comment]
This quite clearly transposes to a Benoni. The built-in opening database CuteChess doesn't handle transpositions, whereas the external program used by the TCEC version does.

**Comment by ilaripih** [comment]
My bad. I thought that ECO codes where based only on the sequence of moves; not the position reached.
